version: '3'
services:
  tapiriik:
    build: .
    environment:
      RABBITMQ_BROKER_URL: "amqp://guest@tapiriik_rabbitmq//"
      MONGO_HOST: "mongodb://root:example@tapiriik_mongo:27017/admin"
      REDIS_HOST: "tapiriik_redis"
      ENDOALT_PROXY_URL: "http://endoalt_proxy:8001"
    ports:
    - "8000:8000"
    volumes:
      - ./persistent:/tapiriik/persistent 
    links:
      - tapiriik_redis
      - tapiriik_mongo
      - tapiriik_rabbitmq
      - endoalt_proxy
    entrypoint: "/bin/bash -c '/tapiriik/bootstrap-docker-compose.sh && python3 manage.py runserver 0.0.0.0:8000'"

  tapiriik_worker:
    build: .
    environment:
      RABBITMQ_BROKER_URL: "amqp://guest@tapiriik_rabbitmq//"
      MONGO_HOST: "mongodb://root:example@tapiriik_mongo:27017/admin"
      REDIS_HOST: "tapiriik_redis"
      ENDOALT_PROXY_URL: "http://endoalt_proxy:8001"
    volumes:
      - ./persistent:/tapiriik/persistent 
    links:
      - tapiriik_redis
      - tapiriik_mongo
      - tapiriik_rabbitmq
      - endoalt_proxy
    entrypoint: "/bin/bash -c '/tapiriik/bootstrap-docker-compose.sh && python3 sync_worker.py ; sleep 10'"
    restart: unless-stopped

  tapiriik_scheduler:
    build: .
    environment:
      RABBITMQ_BROKER_URL: "amqp://guest@tapiriik_rabbitmq//"
      MONGO_HOST: "mongodb://root:example@tapiriik_mongo:27017/admin"
      REDIS_HOST: "tapiriik_redis"
      ENDOALT_PROXY_URL: "http://endoalt_proxy:8001"
    volumes:
      - ./persistent:/tapiriik/persistent 
    links:
      - tapiriik_redis
      - tapiriik_mongo
      - tapiriik_rabbitmq
      - endoalt_proxy
    entrypoint: "/bin/bash -c '/tapiriik/bootstrap-docker-compose.sh && python3 sync_scheduler.py ; sleep 10'"
    restart: unless-stopped

  tapiriik_redis:
    image: redis

  tapiriik_mongo:
    image: mongo 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  tapiriik_rabbitmq:
    image: rabbitmq:3-management

  endoalt_proxy:
    build: tapiriik/services/EndoAlt/proxy/
    restart: unless-stopped
